### ISSUE TITLE
Does not install on raspberry pi

### ISSUE THREAD

**Issue by jbrownkramer** [Dynamsoft/python-barcode#20]
I am running on a raspberry pip model 3b+, python version 3.5.3, pip 20.2.2.  I am using Raspian stretch.  I get the following error:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement dbr (from versions: none)
ERROR: No matching distribution found for dbr
```

**Comment by yushulx** [comment]
@jbrownkramer 3.5 is not supported. You can update Python to 3.6, 3.7 or 3.8. 

![image](https://user-images.githubusercontent.com/2202306/90351900-3c41e100-e074-11ea-8a51-5ab8e9f75985.png)
